### ISSUE TITLE
Let's Get Started

### ISSUE THREAD

**Issue by kopeckylukas** [kopeckylukas/LSHTM_RCS#1]
Hi Everyone, 

Let's get started with our project! Please use this site as a to do list and add any comments, questions or just simply allocated someone to a task. 

Alternatively, we can also use Slack or Asana, but I do not think it is necessary for the scale of our project. 

Thanks, see you around!

**Comment by AmiSaito-17** [comment]
Hello! Looking forward to working with you all!
