### ISSUE TITLE
Commissioner level data

### ISSUE THREAD

**Issue by kopeckylukas** [kopeckylukas/LSHTM_RCS#4]
Hello,

Could I ask you for some help with the commissioner-level data cleaning? 

I have created a script that does all the heavy lifting automatically, but it is time consuming time consuming to run it for all the 71 files. Although the process itself is takes up only couple of seconds, changing path to those files is the annoying part - you need to change the file path as shown in the code below.

The cleaning file is called __'Commissioner data clean.r'__ allocated in the R folder of the repository. 
In order to run the file, pull changes from the repository and change following lines 
```
path <- "data/com_data/2021/OCTOBER-2021-CANCER-WAITING-TIMES-COMMISSIONER-WORKBOOK-PROVISIONAL.xlsx"
period <- as.Date('2021-10-01') #yyy-mm-dd
newName <- "data/com_done/october-21.csv"
```
The first line is the _file you want to clean_
Second is the date of the file **(it is essential for our time series to be precise and in exact same format)**
Third line is the name of our new file, please keep it in format _'month-21.csv'_

The data itself are allocated in the repository _/Data/com_data/_. Extracted files will be saved in _/Data/com_done/_.

I created a [sign up sheet](https://lshtm-my.sharepoint.com/:x:/g/personal/lsh2102097_student_lshtm_ac_uk/EdxR2afAI9pKoHJuv7osHl4BhztFEMijzzZujXrXpQtwQw?e=3GM1J7 ) where you can indicate which files you want to take and the state of your work so we can ensure no one is doing double work.

To upload the data back to the repository, make a commit of your changes and push them back to GitHub as you would do with ordinary files or your code. Before making a commit, please make sure you deselect the _'Commissioner data clean.r'_ from the commit as might result in conflict (conflict usually happen when multiple people edit the same file. Alternatively, you can copy and paste this the code from [this page](https://github.com/kopeckylukas/LSHTM_RCS/blob/main/R/Commissioner%20data%20clean.R) before making a commit. 

Thank you for help, it's much appreciated.

**Comment by AmiSaito-17** [comment]
Done!
